// Demonstration data only. Replace these adapters with validated API responses for deployment.
export const states = [
  { name: 'Arunachal Pradesh', short: 'AR', score: 84, level: 'Critical', rain: 118, alerts: 2, lat: 28.18, lng: 94.4, soil: 81, slope: '31°', elevation: '1,720 m', updated: '12 min ago', event: 'Minor debris flow reported in Upper Subansiri' },
  { name: 'Assam', short: 'AS', score: 43, level: 'Moderate', rain: 74, alerts: 0, lat: 26.2, lng: 92.9, soil: 61, slope: '12°', elevation: '130 m', updated: '15 min ago', event: 'No new landslide record' },
  { name: 'Meghalaya', short: 'ML', score: 67, level: 'High', rain: 102, alerts: 1, lat: 25.58, lng: 91.88, soil: 76, slope: '26°', elevation: '1,430 m', updated: '9 min ago', event: 'Road clearance monitoring, East Khasi Hills' },
  { name: 'Manipur', short: 'MN', score: 58, level: 'High', rain: 89, alerts: 0, lat: 24.66, lng: 93.91, soil: 69, slope: '23°', elevation: '920 m', updated: '17 min ago', event: 'No new landslide record' },
  { name: 'Mizoram', short: 'MZ', score: 52, level: 'Moderate', rain: 82, alerts: 0, lat: 23.16, lng: 92.94, soil: 65, slope: '21°', elevation: '1,040 m', updated: '14 min ago', event: 'No new landslide record' },
  { name: 'Nagaland', short: 'NL', score: 61, level: 'High', rain: 93, alerts: 1, lat: 26.16, lng: 94.56, soil: 72, slope: '27°', elevation: '1,180 m', updated: '11 min ago', event: 'Slope inspection recommended near Kohima' },
  { name: 'Tripura', short: 'TR', score: 31, level: 'Low', rain: 51, alerts: 0, lat: 23.94, lng: 91.98, soil: 54, slope: '9°', elevation: '55 m', updated: '19 min ago', event: 'No new landslide record' },
  { name: 'Sikkim', short: 'SK', score: 79, level: 'Critical', rain: 111, alerts: 1, lat: 27.53, lng: 88.51, soil: 79, slope: '33°', elevation: '2,150 m', updated: '8 min ago', event: 'Watch maintained for North Sikkim corridor' }
];
export const alerts = [
  { state: 'Arunachal Pradesh', location: 'Upper Subansiri', level: 'Warning', reason: '118 mm rainfall and saturated hillslope conditions', action: 'Restrict travel on vulnerable road sections.', time: '12 min ago' },
  { state: 'Sikkim', location: 'North Sikkim corridor', level: 'Watch', reason: 'Elevated slope susceptibility after intense rain', action: 'Continue field observation and community advisory.', time: '18 min ago' },
  { state: 'Meghalaya', location: 'East Khasi Hills', level: 'Watch', reason: 'Rainfall accumulation above district threshold', action: 'Inspect known cut-slope locations.', time: '24 min ago' },
  { state: 'Nagaland', location: 'Kohima periphery', level: 'Watch', reason: 'High soil moisture on steep terrain', action: 'Notify district control room.', time: '31 min ago' }
];
export const riskColor = { Low: '#10b981', Moderate: '#eab308', High: '#f97316', Critical: '#ef4444' };

export const roads = [
  {
    id: 'rd-sk-nh10',
    highway_code: 'NH-10',
    name: 'Siliguri-Gangtok Highway',
    state_code: 'SK',
    district: 'Pakyong / East Sikkim',
    vulnerable_stretch_km: 42.5,
    status: 'RESTRICTED',
    elevation_m: 1650.0,
    lat: 27.25,
    lng: 88.48,
    segment_km_start: 42.3,
    segment_km_end: 45.1,
    start_lat: 27.2380,
    start_lng: 88.4680,
    end_lat: 27.2620,
    end_lng: 88.4920,
    risk_score: 79,
    risk_level: 'Critical',
    rain_24h: 111.0,
    soil_moisture: 79.0,
    slope: '33°',
    landslide_status: 'Active Slope Clearance & Rockfall Watch',
    road_status: 'RESTRICTED',
    last_updated: '8 min ago',
    data_status: 'AVAILABLE'
  },
  {
    id: 'rd-ar-nh13',
    highway_code: 'NH-13',
    name: 'Trans-Arunachal Highway (Subansiri-Siang)',
    state_code: 'AR',
    district: 'Upper Subansiri',
    vulnerable_stretch_km: 68.0,
    status: 'BLOCKED',
    elevation_m: 1820.0,
    lat: 28.12,
    lng: 94.35,
    segment_km_start: 65.2,
    segment_km_end: 68.0,
    start_lat: 28.1050,
    start_lng: 94.3350,
    end_lat: 28.1350,
    end_lng: 94.3650,
    risk_score: 84,
    risk_level: 'Critical',
    is_blocked: true,
    rain_24h: 118.0,
    soil_moisture: 81.0,
    slope: '31°',
    landslide_status: 'Confirmed Landslide Blockage (Debris across Km 66)',
    road_status: 'BLOCKED',
    last_updated: '12 min ago',
    data_status: 'AVAILABLE'
  },
  {
    id: 'rd-ml-nh6',
    highway_code: 'NH-6',
    name: 'Shillong-Silchar Arterial Corridor',
    state_code: 'ML',
    district: 'East Khasi Hills',
    vulnerable_stretch_km: 31.0,
    status: 'RESTRICTED',
    elevation_m: 1350.0,
    lat: 25.48,
    lng: 92.15,
    segment_km_start: null,
    segment_km_end: null,
    start_lat: null,
    start_lng: null,
    end_lat: null,
    end_lng: null,
    risk_score: 67,
    risk_level: 'High',
    rain_24h: 102.0,
    soil_moisture: 76.0,
    slope: '26°',
    landslide_status: 'Slope Creep Monitoring',
    road_status: 'RESTRICTED',
    last_updated: '9 min ago',
    data_status: 'AVAILABLE'
  },
  {
    id: 'rd-nl-nh29',
    highway_code: 'NH-29',
    name: 'Dimapur-Kohima Ghat Section',
    state_code: 'NL',
    district: 'Kohima',
    vulnerable_stretch_km: 24.5,
    status: 'MONITORED',
    elevation_m: 1210.0,
    lat: 25.75,
    lng: 93.92,
    segment_km_start: null,
    segment_km_end: null,
    start_lat: null,
    start_lng: null,
    end_lat: null,
    end_lng: null,
    risk_score: 61,
    risk_level: 'High',
    rain_24h: 93.0,
    soil_moisture: 72.0,
    slope: '27°',
    landslide_status: 'Minor Slumping / Traffic Escort Active',
    road_status: 'MONITORED',
    last_updated: '11 min ago',
    data_status: 'AVAILABLE'
  },
  {
    id: 'rd-as-nh27',
    highway_code: 'NH-27',
    name: 'Guwahati-Nagaon Corridor',
    state_code: 'AS',
    district: 'Kamrup Metro / Morigaon',
    vulnerable_stretch_km: 18.0,
    status: 'OPEN',
    elevation_m: 85.0,
    lat: 26.15,
    lng: 92.10,
    segment_km_start: 12.0,
    segment_km_end: 18.0,
    start_lat: 26.1150,
    start_lng: 92.0500,
    end_lat: 26.1850,
    end_lng: 92.1500,
    risk_score: 43,
    risk_level: 'Medium',
    rain_24h: 74.0,
    soil_moisture: 61.0,
    slope: '12°',
    landslide_status: 'No Active Obstruction',
    road_status: 'OPEN',
    last_updated: '15 min ago',
    data_status: 'AVAILABLE'
  },
  {
    id: 'rd-tr-nh8',
    highway_code: 'NH-8',
    name: 'Agartala-Udaipur Highway',
    state_code: 'TR',
    district: 'West Tripura / Gomati',
    vulnerable_stretch_km: 14.0,
    status: 'OPEN',
    elevation_m: 45.0,
    lat: 23.68,
    lng: 91.45,
    segment_km_start: 8.0,
    segment_km_end: 14.0,
    start_lat: 23.6200,
    start_lng: 91.3800,
    end_lat: 23.7400,
    end_lng: 91.5200,
    risk_score: 31,
    risk_level: 'Low',
    rain_24h: 51.0,
    soil_moisture: 54.0,
    slope: '9°',
    landslide_status: 'Stable Low-Risk Corridor',
    road_status: 'OPEN',
    last_updated: '19 min ago',
    data_status: 'AVAILABLE'
  }
];

