"""Authoritative seed data for NERA 2.0 (North Eastern Region).

Restricted exclusively to the 8 official NER states:
- Arunachal Pradesh (AR)
- Assam (AS)
- Manipur (MN)
- Meghalaya (ML)
- Mizoram (MZ)
- Nagaland (NL)
- Sikkim (SK)
- Tripura (TR)
"""

NER_STATES_SEED = [
    {
        "name": "Arunachal Pradesh",
        "short": "AR",
        "score": 84,
        "level": "Critical",
        "rain": 118.0,
        "alerts": 2,
        "lat": 28.18,
        "lng": 94.40,
        "soil": 81.0,
        "slope": "31°",
        "elevation": "1,720 m",
        "updated": "12 min ago",
        "event": "Minor debris flow reported in Upper Subansiri",
        "data_status": "AVAILABLE"
    },
    {
        "name": "Assam",
        "short": "AS",
        "score": 43,
        "level": "Moderate",
        "rain": 74.0,
        "alerts": 0,
        "lat": 26.20,
        "lng": 92.90,
        "soil": 61.0,
        "slope": "12°",
        "elevation": "130 m",
        "updated": "15 min ago",
        "event": "No new landslide record",
        "data_status": "AVAILABLE"
    },
    {
        "name": "Meghalaya",
        "short": "ML",
        "score": 67,
        "level": "High",
        "rain": 102.0,
        "alerts": 1,
        "lat": 25.58,
        "lng": 91.88,
        "soil": 76.0,
        "slope": "26°",
        "elevation": "1,430 m",
        "updated": "9 min ago",
        "event": "Road clearance monitoring, East Khasi Hills",
        "data_status": "AVAILABLE"
    },
    {
        "name": "Manipur",
        "short": "MN",
        "score": 58,
        "level": "High",
        "rain": 89.0,
        "alerts": 0,
        "lat": 24.66,
        "lng": 93.91,
        "soil": 69.0,
        "slope": "23°",
        "elevation": "920 m",
        "updated": "17 min ago",
        "event": "No new landslide record",
        "data_status": "AVAILABLE"
    },
    {
        "name": "Mizoram",
        "short": "MZ",
        "score": 52,
        "level": "Moderate",
        "rain": 82.0,
        "alerts": 0,
        "lat": 23.16,
        "lng": 92.94,
        "soil": 65.0,
        "slope": "21°",
        "elevation": "1,040 m",
        "updated": "14 min ago",
        "event": "No new landslide record",
        "data_status": "AVAILABLE"
    },
    {
        "name": "Nagaland",
        "short": "NL",
        "score": 61,
        "level": "High",
        "rain": 93.0,
        "alerts": 1,
        "lat": 26.16,
        "lng": 94.56,
        "soil": 72.0,
        "slope": "27°",
        "elevation": "1,180 m",
        "updated": "11 min ago",
        "event": "Slope inspection recommended near Kohima",
        "data_status": "AVAILABLE"
    },
    {
        "name": "Tripura",
        "short": "TR",
        "score": 31,
        "level": "Low",
        "rain": 51.0,
        "alerts": 0,
        "lat": 23.94,
        "lng": 91.98,
        "soil": 54.0,
        "slope": "9°",
        "elevation": "55 m",
        "updated": "19 min ago",
        "event": "No new landslide record",
        "data_status": "AVAILABLE"
    },
    {
        "name": "Sikkim",
        "short": "SK",
        "score": 79,
        "level": "Critical",
        "rain": 111.0,
        "alerts": 1,
        "lat": 27.53,
        "lng": 88.51,
        "soil": 79.0,
        "slope": "33°",
        "elevation": "2,150 m",
        "updated": "8 min ago",
        "event": "Watch maintained for North Sikkim corridor",
        "data_status": "AVAILABLE"
    }
]

INITIAL_ALERTS_SEED = [
    {
        "id": "alert-ar-01",
        "state": "Arunachal Pradesh",
        "location": "Upper Subansiri Corridor",
        "level": "Warning",
        "reason": "118 mm rainfall and saturated hillslope conditions",
        "action": "Restrict travel on vulnerable road sections.",
        "time": "12 min ago",
        "status": "ACTIVE",
        "delivery_status": "SIMULATED_DEMO"
    },
    {
        "id": "alert-sk-01",
        "state": "Sikkim",
        "location": "North Sikkim corridor (NH-10)",
        "level": "Watch",
        "reason": "Elevated slope susceptibility after intense rain",
        "action": "Continue field observation and community advisory.",
        "time": "18 min ago",
        "status": "ACTIVE",
        "delivery_status": "SIMULATED_DEMO"
    },
    {
        "id": "alert-ml-01",
        "state": "Meghalaya",
        "location": "East Khasi Hills",
        "level": "Watch",
        "reason": "Rainfall accumulation above district threshold",
        "action": "Inspect known cut-slope locations.",
        "time": "24 min ago",
        "status": "ACTIVE",
        "delivery_status": "SIMULATED_DEMO"
    },
    {
        "id": "alert-nl-01",
        "state": "Nagaland",
        "location": "Kohima periphery",
        "level": "Watch",
        "reason": "High soil moisture on steep terrain",
        "action": "Notify district control room.",
        "time": "31 min ago",
        "status": "ACTIVE",
        "delivery_status": "SIMULATED_DEMO"
    }
]

VILLAGES_SEED = [
    {
        "id": "vil-ar-01",
        "name": "Daporijo Hills",
        "state_code": "AR",
        "district": "Upper Subansiri",
        "population": 14200,
        "slope_deg": 32.5,
        "risk_score": 83,
        "risk_level": "Critical",
        "lat": 27.98,
        "lng": 94.22
    },
    {
        "id": "vil-sk-01",
        "name": "Chungthang",
        "state_code": "SK",
        "district": "Mangan (North Sikkim)",
        "population": 4800,
        "slope_deg": 34.0,
        "risk_score": 88,
        "risk_level": "Critical",
        "lat": 27.60,
        "lng": 88.65
    },
    {
        "id": "vil-ml-01",
        "name": "Cherrapunjee Ridge",
        "state_code": "ML",
        "district": "East Khasi Hills",
        "population": 11780,
        "slope_deg": 28.0,
        "risk_score": 69,
        "risk_level": "High",
        "lat": 25.29,
        "lng": 91.72
    },
    {
        "id": "vil-nl-01",
        "name": "Jotsoma Slope",
        "state_code": "NL",
        "district": "Kohima",
        "population": 6200,
        "slope_deg": 27.5,
        "risk_score": 64,
        "risk_level": "High",
        "lat": 25.67,
        "lng": 94.07
    },
    {
        "id": "vil-mn-01",
        "name": "Noney Valley",
        "state_code": "MN",
        "district": "Noney",
        "population": 5400,
        "slope_deg": 25.0,
        "risk_score": 59,
        "risk_level": "High",
        "lat": 24.82,
        "lng": 93.60
    },
    {
        "id": "vil-mz-01",
        "name": "Sairang Foothills",
        "state_code": "MZ",
        "district": "Aizawl",
        "population": 7300,
        "slope_deg": 22.0,
        "risk_score": 53,
        "risk_level": "Moderate",
        "lat": 23.78,
        "lng": 92.65
    }
]

ROADS_SEED = [
    {
        "id": "rd-sk-nh10",
        "highway_code": "NH-10",
        "name": "Siliguri-Gangtok Highway",
        "state_code": "SK",
        "district": "Pakyong / East Sikkim",
        "vulnerable_stretch_km": 42.5,
        "status": "RESTRICTED",
        "elevation_m": 1650.0,
        "lat": 27.25,
        "lng": 88.48,
        "segment_km_start": 42.3,
        "segment_km_end": 45.1,
        "start_lat": 27.2380,
        "start_lng": 88.4680,
        "end_lat": 27.2620,
        "end_lng": 88.4920,
        "risk_score": 79,
        "risk_level": "Critical",
        "rain_24h": 111.0,
        "soil_moisture": 79.0,
        "slope": "33°",
        "landslide_status": "Active Slope Clearance & Rockfall Watch",
        "road_status": "RESTRICTED",
        "last_updated": "8 min ago",
        "data_status": "AVAILABLE",
    },
    {
        "id": "rd-ar-nh13",
        "highway_code": "NH-13",
        "name": "Trans-Arunachal Highway (Subansiri-Siang)",
        "state_code": "AR",
        "district": "Upper Subansiri",
        "vulnerable_stretch_km": 68.0,
        "status": "BLOCKED",
        "elevation_m": 1820.0,
        "lat": 28.12,
        "lng": 94.35,
        "segment_km_start": 65.2,
        "segment_km_end": 68.0,
        "start_lat": 28.1050,
        "start_lng": 94.3350,
        "end_lat": 28.1350,
        "end_lng": 94.3650,
        "risk_score": 84,
        "risk_level": "Critical",
        "rain_24h": 118.0,
        "soil_moisture": 81.0,
        "slope": "31°",
        "landslide_status": "Confirmed Landslide Blockage (Debris across Km 66)",
        "road_status": "BLOCKED",
        "last_updated": "12 min ago",
        "data_status": "AVAILABLE",
    },
    {
        "id": "rd-ml-nh6",
        "highway_code": "NH-6",
        "name": "Shillong-Silchar Arterial Corridor",
        "state_code": "ML",
        "district": "East Khasi Hills",
        "vulnerable_stretch_km": 31.0,
        "status": "RESTRICTED",
        "elevation_m": 1350.0,
        "lat": 25.48,
        "lng": 92.15,
        "segment_km_start": None,
        "segment_km_end": None,
        "start_lat": None,
        "start_lng": None,
        "end_lat": None,
        "end_lng": None,
        "risk_score": 67,
        "risk_level": "High",
        "rain_24h": 102.0,
        "soil_moisture": 76.0,
        "slope": "26°",
        "landslide_status": "Slope Creep Monitoring",
        "road_status": "RESTRICTED",
        "last_updated": "9 min ago",
        "data_status": "AVAILABLE",
    },
    {
        "id": "rd-nl-nh29",
        "highway_code": "NH-29",
        "name": "Dimapur-Kohima Ghat Section",
        "state_code": "NL",
        "district": "Kohima",
        "vulnerable_stretch_km": 24.5,
        "status": "MONITORED",
        "elevation_m": 1210.0,
        "lat": 25.75,
        "lng": 93.92,
        "segment_km_start": None,
        "segment_km_end": None,
        "start_lat": None,
        "start_lng": None,
        "end_lat": None,
        "end_lng": None,
        "risk_score": 61,
        "risk_level": "High",
        "rain_24h": 93.0,
        "soil_moisture": 72.0,
        "slope": "27°",
        "landslide_status": "Minor Slumping / Traffic Escort Active",
        "road_status": "MONITORED",
        "last_updated": "11 min ago",
        "data_status": "AVAILABLE",
    },
    {
        "id": "rd-as-nh27",
        "highway_code": "NH-27",
        "name": "Guwahati-Nagaon Corridor",
        "state_code": "AS",
        "district": "Kamrup / Marigaon",
        "vulnerable_stretch_km": 18.0,
        "status": "MONITORED",
        "elevation_m": 85.0,
        "lat": 26.15,
        "lng": 92.10,
        "segment_km_start": 12.0,
        "segment_km_end": 18.0,
        "start_lat": 26.1200,
        "start_lng": 92.0500,
        "end_lat": 26.1700,
        "end_lng": 92.1400,
        "risk_score": 43,
        "risk_level": "Medium",
        "rain_24h": 74.0,
        "soil_moisture": 61.0,
        "slope": "12°",
        "landslide_status": "No Active Obstruction",
        "road_status": "OPEN",
        "last_updated": "15 min ago",
        "data_status": "AVAILABLE",
    },
    {
        "id": "rd-tr-nh8",
        "highway_code": "NH-8",
        "name": "Agartala-Udaipur Highway",
        "state_code": "TR",
        "district": "West Tripura",
        "vulnerable_stretch_km": 14.0,
        "status": "OPEN",
        "elevation_m": 45.0,
        "lat": 23.65,
        "lng": 91.50,
        "segment_km_start": 8.0,
        "segment_km_end": 14.0,
        "start_lat": 23.6100,
        "start_lng": 91.4500,
        "end_lat": 23.6800,
        "end_lng": 91.5400,
        "risk_score": 31,
        "risk_level": "Low",
        "rain_24h": 51.0,
        "soil_moisture": 54.0,
        "slope": "9°",
        "landslide_status": "Stable Low-Risk Corridor",
        "road_status": "OPEN",
        "last_updated": "19 min ago",
        "data_status": "AVAILABLE",
    },
]

INITIAL_REPORTS_SEED = [
    {
        "id": "rep-seed-01",
        "citizen_name": "Tashi Bhutia",
        "contact": "+91-9876543201",
        "incident_type": "Rockfall & Mudflow Blockage",
        "description": "Major debris flow across NH-13 km 66.2. Road completely impassable; emergency clearance underway.",
        "lat": 28.1250,
        "lng": 94.3480,
        "media_url": None,
        "status": "verified",
        "verified_by": "usr-officer-01",
        "officer_notes": "Ground verification confirmed by District Disaster Management Officer. Road diversion active.",
        "created_at": "2026-09-10T14:32:00Z",
    },
    {
        "id": "rep-seed-02",
        "citizen_name": "Pema Lyngdoh",
        "contact": "+91-9876543202",
        "incident_type": "Slope Creep & Tension Cracks",
        "description": "Citizen observed hillside tension fissures and drainage overflow along NH-6 shoulder.",
        "lat": 25.4950,
        "lng": 92.1620,
        "media_url": None,
        "status": "pending",
        "verified_by": None,
        "officer_notes": None,
        "created_at": "2026-09-11T05:15:00Z",
    },
    {
        "id": "rep-seed-03",
        "citizen_name": "Sonam Lepcha",
        "contact": "+91-9876543203",
        "incident_type": "Debris Slide on Cut Slope",
        "description": "Rainfall saturated cut-slope failure on North Sikkim route. Single lane movement open for emergency response vehicles.",
        "lat": 27.5200,
        "lng": 88.5250,
        "media_url": None,
        "status": "verified",
        "verified_by": "usr-officer-01",
        "officer_notes": "Verified by Sikkim SDRF field inspection. Warning signs placed.",
        "created_at": "2026-09-10T18:40:00Z",
    },
]

HISTORICAL_LANDSLIDES_SEED = [
    {
        "id": "hist-01",
        "location": "Upper Subansiri, AR",
        "state_code": "AR",
        "date": "Jul 2024",
        "severity": "High",
        "trigger": "Prolonged rainfall",
        "lat": 28.15,
        "lng": 94.38
    },
    {
        "id": "hist-02",
        "location": "East Khasi Hills, ML",
        "state_code": "ML",
        "date": "Jun 2024",
        "severity": "Moderate",
        "trigger": "Slope saturation",
        "lat": 25.55,
        "lng": 91.85
    },
    {
        "id": "hist-03",
        "location": "North Sikkim, SK",
        "state_code": "SK",
        "date": "Oct 2023",
        "severity": "Critical",
        "trigger": "Extreme rainfall",
        "lat": 27.55,
        "lng": 88.52
    },
    {
        "id": "hist-04",
        "location": "Noney Tupul Yard, MN",
        "state_code": "MN",
        "date": "Jun 2022",
        "severity": "Critical",
        "trigger": "Continuous monsoon deluge & cut-slope failure",
        "lat": 24.81,
        "lng": 93.62
    }
]

INFRASTRUCTURE_POINTS_SEED = [
    {
        "id": "infra-hosp-01",
        "name": "District Hospital Mangan",
        "category": "Hospital",
        "state_code": "SK",
        "lat": 27.51,
        "lng": 88.53,
        "capacity_beds": 120,
        "emergency_shelter": 1
    },
    {
        "id": "infra-sch-01",
        "name": "Daporijo Higher Secondary School",
        "category": "School",
        "state_code": "AR",
        "lat": 27.99,
        "lng": 94.22,
        "capacity_beds": 350,
        "emergency_shelter": 1
    },
    {
        "id": "infra-brg-01",
        "name": "Teesta IV Suspension Bridge",
        "category": "Bridge",
        "state_code": "SK",
        "lat": 27.42,
        "lng": 88.50,
        "capacity_beds": 0,
        "emergency_shelter": 0
    },
    {
        "id": "infra-pwr-01",
        "name": "Nongstoin 132kV Substation",
        "category": "Power",
        "state_code": "ML",
        "lat": 25.52,
        "lng": 91.27,
        "capacity_beds": 0,
        "emergency_shelter": 0
    },
    {
        "id": "infra-hosp-02",
        "name": "Civil Hospital Nongstoin",
        "category": "Hospital",
        "state_code": "ML",
        "lat": 25.51,
        "lng": 91.26,
        "capacity_beds": 90,
        "emergency_shelter": 1
    },
    {
        "id": "infra-sch-02",
        "name": "Kohima Government Higher Secondary",
        "category": "School",
        "state_code": "NL",
        "lat": 25.67,
        "lng": 94.11,
        "capacity_beds": 500,
        "emergency_shelter": 1
    },
    {
        "id": "infra-brg-02",
        "name": "Tuivawl River Road Bridge",
        "category": "Bridge",
        "state_code": "MZ",
        "lat": 23.95,
        "lng": 92.95,
        "capacity_beds": 0,
        "emergency_shelter": 0
    },
    {
        "id": "infra-hosp-03",
        "name": "District Hospital Champhai",
        "category": "Hospital",
        "state_code": "MZ",
        "lat": 23.47,
        "lng": 93.33,
        "capacity_beds": 100,
        "emergency_shelter": 1
    }
]

VOLUNTEERS_SEED = [
    {
        "id": "vol-01",
        "name": "Tashi Wangchuk",
        "state_code": "SK",
        "district": "North Sikkim",
        "role": "Community First Responder",
        "badge": "Trusted Reporter",
        "reports_verified": 8,
        "status": "ACTIVE_STANDBY"
    },
    {
        "id": "vol-02",
        "name": "Dorjee Khandu",
        "state_code": "AR",
        "district": "Upper Subansiri",
        "role": "Disaster Relief Volunteer",
        "badge": "Verified Reporter",
        "reports_verified": 5,
        "status": "DISPATCH_READY"
    },
    {
        "id": "vol-03",
        "name": "Lalremruata Sailo",
        "state_code": "MZ",
        "district": "Champhai",
        "role": "Local HAM Radio / Volunteer",
        "badge": "Trusted Reporter",
        "reports_verified": 11,
        "status": "ACTIVE_STANDBY"
    },
    {
        "id": "vol-04",
        "name": "Bikash Debbarma",
        "state_code": "TR",
        "district": "Dhalai",
        "role": "Youth Disaster Response",
        "badge": "Verified Reporter",
        "reports_verified": 4,
        "status": "ACTIVE_STANDBY"
    }
]


